export const GET_QUESTIONS_API = 'GET_QUESTIONS_API';
export const GET_QUESTIONS_API_LOADING = 'GET_QUESTIONS_API_LOADING';
export const GET_QUESTIONS_API_ERROR = 'GET_QUESTIONS_API_ERROR';
export const GET_QUESTIONS_API_ASYNC = 'GET_QUESTIONS_API_ASYNC';
export const RESET_QUESTIONS = 'RESET_QUESTIONS';
export const RESET_QUESTIONS_ASYNC = 'RESET_QUESTIONS_ASYNC';

export const SET_RESPONSE = 'SET_RESPONSE';
export const SET_RESPONSE_ASYNC = 'SET_RESPONSE_ASYNC';
export const RESET_RESPONSES = 'RESET_RESPONSES';
export const RESET_RESPONSES_ASYNC = 'RESET_RESPONSES_ASYNC';